export const CATEGORIES = [
  {
    id: 'UG',
    label: 'UG',
    icon: '🥃',
    color: '#1a3a5c',
    bgColor: '#e8f0f7',
    type: 'qpn',
    brandCount: 13,
  },
  {
    id: 'DCSL',
    label: 'DCSL',
    icon: '🍸',
    color: '#7c3d1a',
    bgColor: '#fdf0e8',
    type: 'qpn',
    brandCount: 28,
  },
  {
    id: 'IDL',
    label: 'IDL',
    icon: '🥂',
    color: '#1a5c3d',
    bgColor: '#eef7f0',
    type: 'qpn',
    brandCount: 25,
  },
  {
    id: 'RL',
    label: 'Rockland',
    icon: '🍷',
    color: '#5c1a3d',
    bgColor: '#f7eef7',
    type: 'qpn',
    brandCount: 24,
  },
  {
    id: 'LION',
    label: 'Lion Brewery',
    icon: '🍺',
    color: '#7c5a1a',
    bgColor: '#fdf7e8',
    type: 'beer',
    brandCount: 12,
  },
  {
    id: 'DCSLBEER',
    label: 'DCSL Beer',
    icon: '🍻',
    color: '#1a2e7c',
    bgColor: '#eef0fd',
    type: 'beer',
    brandCount: 10,
  },
];

export const BRANDS = {
  UG: [
    'UG EXTRA SPECIAL ARRACK',
    'UG SPECIAL ARRACK',
    'LEMONARK ARRACK',
    'ORIGIN PREMIUM WHITE ARRACK',
    'GOLD STAR ARRACK',
    'VAT 6 ARRACK',
    'ISLAND STAGE WHISKY',
    'POYN VODKA',
    'MORPHO LONDON DRY GIN',
    'APPLEARK ARRACK',
    'LEO ARRACK',
    'POYN VODKA-GREEN APPLE',
    'ROYAL BLACK ARRACK',
  ],
  DCSL: [
    'EXTRA SPECIAL',
    'SPECIAL ARRACK',
    'WHITE LABEL ARRACK',
    'BLUE LABEL ARRACK',
    'COCONUT ARRACK',
    'OLD ARRACK',
    'V.S.O.A. PREMIUM',
    'D.D.A',
    'SRI LANKA ARRACK',
    'ARGENTE',
    'NARIKELA',
    'ECONOMY PLUS',
    'DOUBLE BARREL',
    'BLACK OPAL ARRACK',
    'TRIPLE BLUE ARRACK',
    'PERICEYL APPLE ARRACK',
    'PERICEYL MANGO ARRACK',
    'HOUSE OF TILBURY WHISKY',
    'TILSIDER WHISKY',
    'GALERIE BRANDY',
    'GALERIE PREMIUM BRANDY',
    'FRANKLIN BRANDY',
    'BALMORAL DARK RUM',
    'BALMORAL WHITE RUM',
    'PETROF VODKA',
    'EXCELLA TEQUILA',
    'FLINTON LONDON GIN',
    'FLINTON LEMON GIN',
  ],
  IDL: [
    'OLD RESERVE ARRACK',
    'OLD ARRACK',
    'BLACK LABEL',
    'RED LABEL',
    'GREEN LABEL',
    'GOLD LABEL',
    'WHITE LABEL',
    'WHITE DIAMOND',
    'WHITE DIAMOND LEMON',
    'WHITE DIAMOND APPLE',
    'BLUE SAPPHIRE',
    'CLUB 07',
    'OLD CASK',
    'CAVELIER',
    'ASCOT DRY GIN',
    'ASCOT LEMON GIN',
    'RITZ BRANDY',
    'CHERRY BRANDY',
    'V & A WHISKEY',
    'CALYPSO RED RUM',
    'B. BACCARDI RUM',
    'W. BACCARDI RUM',
    'ERISTOFF VODKA',
    'CELEBRATION VODKA',
    'VSA GOLD',
  ],
  RL: [
    'VAT 9 (WITH BOX)',
    'VAT 9 (WITHOUT BOX)',
    'VAT 9',
    'EXTRA OLD ARRACK',
    'ROCKLAND OLD ARRACK',
    'HALMILLA OLD ARRACK',
    'DD ARRACK',
    'COCONUT ARRACK',
    "GOVERNOR'S CHOICE",
    'NAVY SEAL',
    'ENGLISH APPLE ARRACK',
    'DRY GIN',
    'LEMON GIN',
    'PREMIUM RED RUM',
    'PREMIUM WHITE RUM',
    'HANAPIER BRANDY (WITH BOX)',
    'HANAPIER BRANDY (WITHOUT BOX)',
    'HANAPIER BRANDY',
    'OLD KEG WHISKEY',
    'OLD KEG DOUBLE BLEND WHISKEY',
    'KEROFF VODKA',
    'ROSKA VODKA',
    'NAPOLEON BRANDY',
    'EX WHITE',
  ],
  LION: [
    'LION LAGER',
    'CARLSBERG INTERNATIONAL PREMIUM',
    'LION STOUT',
    'LION STRONG',
    'CARLSBERG PREMIUM SPECIAL BREW',
    'RYDERS WILD APPLE',
    'RYDERS GINGER',
    'SOMERSBY APPLE',
    'SOMERSBY BLACK BERRY',
    'CARLSBERG PREMIUM SMOOTH DRAUGHT',
    'GRAND BLONDE',
    'LION TRUEBORN',
  ],
  DCSLBEER: [
    'DCSL LAGER',
    'DCSL STRONG',
    'DCSL STOUT',
    'TIGER BLACK',
    'BISON STRONG',
    'ALIYA STRONG',
    'ALIYA LAGER',
    'BISON BREEZE',
    'BISON STOUT',
    'ANCHOR STRONG',
  ],
};

export const QPN_COLUMNS = ['Q', 'P', 'N'];
export const BEER_COLUMNS = ['625ml Btl', '500ml Cane', '330ml Cane', '500ml Btl', '325ml Btl'];

export const getColumns = (type) =>
  type === 'beer' ? BEER_COLUMNS : QPN_COLUMNS;

export const APP_COLORS = {
  primary: '#1a3a5c',
  primaryDark: '#0e2440',
  primaryLight: '#2a5278',
  white: '#ffffff',
  background: '#f5f6fa',
  surface: '#ffffff',
  border: '#e2e8f0',
  textPrimary: '#1a202c',
  textSecondary: '#718096',
  textHint: '#a0aec0',
  success: '#2e7d32',
  successBg: '#e8f5e9',
  warning: '#856404',
  warningBg: '#fff3cd',
  danger: '#842029',
  dangerBg: '#f8d7da',
  pending: '#7c4d00',
  pendingBg: '#fff8e1',
};
